### ISSUE TITLE
Investigate/Add skywalking-eyes license header check to project

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#1105]
### Terms

- [x] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [x] I agree to follow activist's [Code of Conduct](.github/CODE_OF_CONDUCT.md)

### Description

In the most recent dev sync we discussed how to make sure that we have SPDA license identifiers at the top of all files. The best way to do this seems to be to use [skywalking-eyes from Apache](https://github.com/apache/skywalking-eyes). This issue would be to add in a new workflow to run on PRs to run this GitHub action via the following snippet:

```yaml
- name: Check License Header
  uses: apache/skywalking-eyes/header@main  
```

Let's also discuss include the check dependency license functionality :)

### Contribution

Happy to work with someone on this and review when there's a PR 😊

**Comment by hboppana** [comment]
Hey, this issue would be my first open source contribution on Github. Would be happy to resolve it if help is needed!

**Comment by andrewtavis** [comment]
We'd be happy to work with you on this, @hboppana! Please let us know if you have any questions :)

**Comment by Abhi-Bohora** [comment]
Hello, @andrewtavis I have decided to take a look into this since it's been more than a week @hboppana might be busy. I wanted to ask a question. Is this `.licenserc.yaml` would be enough or am I missing something ? I have tested this locally, It worked fine except one file that didn't have license as you can see in the screenshot. Thanks 🙏 

![Image](https://github.com/user-attachments/assets/c7786552-0a1c-4119-a144-3835f1111682)

`.licenserc.yaml`
```yaml
 header:
  license:
    content: "SPDX-License-Identifier: AGPL-3.0-or-later"
  paths:
    - '**/*.vue'
    - '**/*.ts'
    - '**/*.test.ts'
    - '**/*.d.ts'
    - '**/*.py'
  paths-ignore:
    - 'dist'
    - 'node_modules'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - '**/__pycache__/**'
    - '**/.git/**'
    - '**/*__init__.py'
  comment: on-failure
  license-location-threshold: 10
```
