### ISSUE TITLE
Investigate and update Yarn install process (Yarn PnP and Zero-installs)

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#1111]
### Terms

- [x] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [x] I agree to follow activist's [Code of Conduct](.github/CODE_OF_CONDUCT.md)

### Description

In #1107 we updated to Yarn v4.x. This issue is to investigate and update the current Yarn process where we'd make use of the modern features of Yarn.

Specifically we would:
- Remove `node_modules`
- Switch over to a version controlled `.yarn` directory such that we don't need to install
- Update `.gitignore` to ignore the needed files ([docs](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored))

The following documentation would be helpful for this:
- [yarnpkg.com/features/caching](https://yarnpkg.com/features/caching)

> [!NOTE]
> We need to make sure that this will also work for our Netlify builds.

### Contribution

Happy to discuss this and support someone who has interest in working on it! 😊

**Comment by Abhi-Bohora** [comment]
Hello @andrewtavis I am looking into this, I will update to you soon. In the mean time can you please assign this issue to me. 😊

**Comment by andrewtavis** [comment]
Hey @Abhi-Bohora 👋 Another person wanted to work on this, but I'll check with them and see if there's something else that's of interest :) For now it's ok to continue, and thanks for your enthusiasm in working with us 😊

**Comment by andrewtavis** [comment]
Quick note from a call, @Abhi-Bohora: The other contributor is happy if you'd like to take this on :) Please let us know if there's anything we can do to support! 😊

**Comment by Abhi-Bohora** [comment]
Hello @andrewtavis I have tried to migrate this but there seems to be some problems with the dependencies especially with `@nuxt/kit` while using yarn plug and play.  i have tracked the issue and got here https://github.com/nuxt/nuxt/issues/26750 they are suggesting `nodeLinker: node_modules` but i think we don't want that when using `pnp` the goal was to remove `node_modules` and load the dependencies from cache. if you have any suggestion or anyone might suggest something regarding this issue that might be great help. 
i tried to use this setting in `.yarnrc.yml` 
```yml
# .yarnrc.yml
nodeLinker: pnp
enableGlobalCache: false
enableScripts: true
pnpMode: loose
enableTransparentWorkspaces: true

packageExtensions:
  "nuxt@*":
    dependencies:
      "@nuxt/kit": "*"
      "@nuxt/schema": "*"
      "pathe": "*"
      "unimport": "*"
      "nitropack": "*"
  "@nuxt/kit@*":
    dependencies:
      "@nuxt/schema": "*"
      "pathe": "*"
      "unimport": "*"
      "nitropack": "*"
  "@nuxt/cli@*":
    dependencies:
      "@nuxt/kit": "*"
      "@nuxt/schema": "*"
  "@nuxt/schema@*":
    dependencies:
      "@nuxt/kit": "*"
      "pathe": "*"
  "nitropack@*":
    dependencies:
      "pathe": "*"

```
i got error while running `yarn install` and this is the error contents of the log file 
```bash
# This file contains the result of Yarn building a package (activist@workspace:.)
# Script name: postinstall


[41m[30m ERROR [39m[49m Your application tried to access @nuxt/kit, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: @nuxt/kit (via "@nuxt\kit")
Required by: C:\Users\abhis\Desktop\os\activist\frontend\

Require stack:
- C:\Users\abhis\Desktop\os\activist\frontend\_index.js

  
  Required package: @nuxt/kit ([36mvia "@nuxt\kit"[39m)
  Required by: 
  
  Require stack:
  - _index.js
  [90mat [39mrequire$$0.Module._resolveFilename ([36m.pnp.cjs:32198:13[39m)
  [90mat [39mFunction.resolve ([36mnode:internal/modules/helpers:190:19[39m)
  [90mat [39mjitiResolve ([36m.yarn\cache\jiti-npm-2.4.2-d980cbb540-4ceac133a0.zip\node_modules\jiti\dist\jiti.cjs:1:187220[39m)
  [90mat [39mjitiRequire ([36m.yarn\cache\jiti-npm-2.4.2-d980cbb540-4ceac133a0.zip\node_modules\jiti\dist\jiti.cjs:1:189288[39m)
  [90mat [39mFunction.import ([36m.yarn\cache\jiti-npm-2.4.2-d980cbb540-4ceac133a0.zip\node_modules\jiti\dist\jiti.cjs:1:199778[39m)
  [90mat [39mloadKit ([36m/C:/Users/abhis/Desktop/os/activist/frontend/.yarn/cache/@nuxt-cli-npm-3.20.0-b9d9d55aec-043dc306f5.zip/node_modules/@nuxt/cli/dist/shared/cli.DlcAx0De.mjs:8:32[39m)
  [90mat [39masync Object.run ([36m/C:/Users/abhis/Desktop/os/activist/frontend/.yarn/cache/@nuxt-cli-npm-3.20.0-b9d9d55aec-043dc306f5.zip/node_modules/@nuxt/cli/dist/chunks/prepare.mjs:29:49[39m)
  [90mat [39masync runCommand ([36m/C:/Users/abhis/Desktop/os/activist/frontend/.yarn/cache/citty-npm-0.1.6-60b76c16d8-d26ad82a9a.zip/node_modules/citty/dist/index.mjs:316:16[39m)
  [90mat [39masync runCommand ([36m/C:/Users/abhis/Desktop/os/activist/frontend/.yarn/cache/citty-npm-0.1.6-60b76c16d8-d26ad82a9a.zip/node_modules/citty/dist/index.mjs:307:11[39m)
  [90mat [39masync runMain ([36m/C:/Users/abhis/Desktop/os/activist/frontend/.yarn/cache/citty-npm-0.1.6-60b76c16d8-d26ad82a9a.zip/node_modules/citty/dist/index.mjs:445:7[39m) 



[41m[30m ERROR [39m[49m Your application tried to access @nuxt/kit, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: @nuxt/kit (via "@nuxt\kit")
Required by: C:\Users\abhis\Desktop\os\activist\frontend\

Require stack:
- C:\Users\abhis\Desktop\os\activist\frontend\_index.js
```
