### ISSUE TITLE
Add skywalking-eyes license header check to pre-commit

### ISSUE THREAD

**Issue by andrewtavis** [activist-org/activist#1273]
### Terms

- [x] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [x] I agree to follow activist's [Code of Conduct](.github/CODE_OF_CONDUCT.md)

### Description

Per discussions in the sync yesterday we decided to add [skywalking-eyes](https://github.com/apache/skywalking-eyes) that we have a PR test for to the [pre-commit](https://pre-commit.com/) hooks. Forgetting the license header has been a consistent problem for contributors new and old, and having it warned locally would be best. GPL code that I've found that seems to do this is [gitlab.nrao.edu/ssa/~/.pre-commit-config.yaml](https://gitlab.nrao.edu/ssa/workspaces/-/blob/2.8.3-DEVELOPMENT/.pre-commit-config.yaml). Maybe something similar can be done for us.

### Contribution

Happy to discuss and work on this! Time to implement was longer than expected, so making an issue 😊

**Comment by andrewtavis** [comment]
Based on what I'm seeing [here](https://github.com/mrsimonemms/pre-commit-hooks/blob/6509413bb0254e946f035686ffae70f2d0ddb0e6/.pre-commit-hooks.yaml#L46) it looks like this needs to be ran via Go directly.

**Comment by andrewtavis** [comment]
CC @to-sta and @mattburnett-repo - FYI this doesn't look like it's direct plug and play :)

**Comment by to-sta** [comment]
I thought checking license headers might be a good exercise to try out [zig](https://ziglang.org/), so I build a simple executable that checks files or a directory for the specified SPDX license header `APGL-3,0-or-later`.

Tried it on the whole backend directory:
```bash
All files contain the required license
Elapsed time: 249526 microseconds (0.250 seconds)
```

It is pretty fast 😄. 

It also works well with pre-commit if I use it locally:

```
repos:
  - repo: local
    hooks:
      - id: zig-hook
        name: zig-hook
        entry: ./zig-out/bin/spdx_checker.exe
        language: system
        pass_filenames: true
        args: [-l, AGPL-3.0-or-later, -f, .py, -f, .vue]
``` 

But I don't know how to make it work with pre-commit besides running it local.
