### ISSUE TITLE
Backend not connecting to database

### ISSUE THREAD

**Issue by henrque** [activist-org/activist#403]
### Terms

- [X] I have searched all [open bug reports](https://github.com/activist-org/activist/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

When trying to run the project I noticed that the backend was not running, after looking the logs I found the error 
```
2023-09-23 15:14:17 django.db.utils.OperationalError: could not connect to server: Connection refused
2023-09-23 15:14:17     Is the server running on host "localhost" (127.0.0.1) and accepting
2023-09-23 15:14:17     TCP/IP connections on port 5432?
2023-09-23 15:14:17 could not connect to server: Address not available
2023-09-23 15:14:17     Is the server running on host "localhost" (::1) and accepting
2023-09-23 15:14:17     TCP/IP connections on port 5432?
```

**Comment by andrewtavis** [comment]
Hey @henrque 👋 Thanks for opening the issue 😊 @to-sta and I just discussed this in the Code Night 🌙 call and 5708cd1 should fix this. If you already have converted over the `.env.example` file to `.env` (looks like you have), then you'll need to `cp .env.example .env` again :)

Can you try pulling and copying and let us know if it works?

**Comment by henrque** [comment]
It worked just fine, but I have a question. Would it be a good idea to change the db ports in docker-compose.yml to be like this?
```
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
```
At the same time, change the DATABASE_PORT of the backend to point to 5432 hardcoded. The way it is now gives an error because Postgres executes on port 5432 by default, and if I change it to another port, the backend can't connect. For example, if I set it to port 5433 I get the error:
![image](https://github.com/activist-org/activist/assets/43590514/7f7820f2-efb9-46c1-bda0-fe6ed372581d)
