### ISSUE TITLE
standardizing github workflows and consoldiating frontend check

### ISSUE THREAD

**Issue by to-sta** [activist-org/activist#431]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We currently have 3 GitHub workflows (excl. the pr_maintainer_checklist 😄)

1. `pr_backend_formatting_check.yaml`
2. `pr_frontend_formatting_check.yaml`
3. `pr_ts_typecheck.yaml`

<ins>Tasks:</ins>
1. Rename `pr_backend_formatting_check` to `ci_backend`
2. We use different package manager on the frontend side for workflows (yarn, npm), let's standardize that. 

We should also be more specific, here we run black, but what does it actually do? We check the formatting.

```yaml
- name: Run Black
  uses: psf/black@stable
  with:
    options: --check --verbose --exclude "migrations/"
    src: ./backend

- name: Run ruff
  run: ruff ./backend

- name: Run mypy - Static Type Checking
  run: mypy ./backend --config-file ./backend/mypy.ini
```

@andrewtavis 
What you say about consoldating the `pr_ts_typecheck` and `pr_frontend_formatting_check` to `pr_ci_frontend`? 

### Contribution

Happy to answer any question, regarding this issue 😃.
